name: cloudflare-ddns
services:
  app:
    image: favonia/cloudflare-ddns:latest
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    environment:
      CF_API_TOKEN: ''
      DOMAINS: ''
      PROXIED: ''
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: ''
        - container: PGID
          description:
            en_us: ''
        - container: CF_API_TOKEN
          description:
            en_us: ''
        - container: DOMAINS
          description:
            en_us: ''
        - container: PROXIED
          description:
            en_us: ''
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: Cloudflare DDNS - A small and fast DDNS updater for Cloudflare.
  tagline:
    en_us: Cloudflare Ddns - A Small And Fast Ddns Updater For Cloudflare.
  developer: ''
  author: WisdomSky
  icon: https://raw.githubusercontent.com/pi-hosted/pi-hosted/master/images/cloudflare-ddns.png
  thumbnail: https://raw.githubusercontent.com/pi-hosted/pi-hosted/master/images/cloudflare-ddns.png
  title:
    en_us: Cloudflare Ddns
  category: DNS
